import zynthalic_chiasmus as core
import os
import datetime

# ---------------------------------------------------------
# CSS STYLING (The "Professional" Look)
# ---------------------------------------------------------
HTML_TEMPLATE = """
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Zynthalic Codex</title>
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Cormorant+Garamond:ital,wght@0,400;0,600;1,400&family=Noto+Serif+KR:wght@400;700&display=swap');

        body {{
            background-color: #f4f1ea;
            color: #2c2c2c;
            font-family: 'Cormorant Garamond', serif;
            margin: 0;
            padding: 40px;
            display: flex;
            justify-content: center;
        }}
        .container {{
            max-width: 1000px;
            width: 100%;
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 60px;
            border-left: 1px solid #dcdcdc;
            padding-left: 40px;
        }}
        h1 {{
            grid-column: 1 / -1;
            text-align: center;
            font-weight: 400;
            letter-spacing: 4px;
            text-transform: uppercase;
            margin-bottom: 60px;
            color: #8b0000;
        }}
        .english-col {{
            color: #666;
            line-height: 1.8;
            font-size: 18px;
            text-align: justify;
        }}
        .zynthalic-col {{
            color: #000;
            line-height: 1.8;
            font-size: 19px;
            text-align: justify;
            font-style: italic;
        }}
        .sigil {{
            font-family: 'Noto Serif KR', serif;
            font-weight: bold;
            color: #8b0000;
            font-style: normal;
            margin-left: 8px;
            cursor: help;
            font-size: 1.2em;
        }}
        .word {{
            position: relative;
            cursor: pointer;
            text-decoration: none;
            border-bottom: 1px dotted #aaa;
        }}
        .word:hover {{
            color: #8b0000;
            border-bottom: 1px solid #8b0000;
        }}
        /* Tooltip magic */
        .word:hover::after {{
            content: attr(data-origin);
            position: absolute;
            bottom: 100%;
            left: 50%;
            transform: translateX(-50%);
            background: #333;
            color: #fff;
            padding: 5px 10px;
            border-radius: 4px;
            font-size: 12px;
            font-family: sans-serif;
            font-style: normal;
            white-space: nowrap;
            z-index: 10;
            box-shadow: 0 4px 6px rgba(0,0,0,0.1);
        }}
        .footer {{
            grid-column: 1 / -1;
            margin-top: 80px;
            border-top: 1px solid #ccc;
            padding-top: 20px;
            font-size: 12px;
            text-align: center;
            color: #888;
        }}
    </style>
</head>
<body>

<div class="container">
    <h1>The Zynthalic Codex</h1>
    
    <div class="english-col">
        {english_html}
    </div>

    <div class="zynthalic-col">
        {zynthalic_html}
    </div>
    
    <div class="footer">
        Generated by Zyntalic Core v1.0 | {timestamp}
    </div>
</div>

</body>
</html>
"""

# ---------------------------------------------------------
# PUBLISHING LOGIC
# ---------------------------------------------------------

def publish_book(text_input, filename="Codex_Page_1.html"):
    import re
    
    # Split into sentences
    sentences = re.split(r'(?<=[.!?])\s+', text_input)
    
    english_paragraphs = []
    zynthalic_paragraphs = []
    
    print(f"Publishing {len(sentences)} sentences to HTML...")

    for sent in sentences:
        if not sent.strip(): 
            continue
        
        # 1. Translate using Core Logic
        raw_words = sent.split()
        trans_words_html = []
        clean_text_for_analysis = []
        
        for w in raw_words:
            clean = "".join(filter(str.isalpha, w))
            clean_text_for_analysis.append(clean)
            
            if clean:
                # Generate word - using the function from your core module
                # Make sure this function exists in zynthalic_chiasmus
                z_word = core.generate_latin_word(clean)
                
                # Get Origin (Anchor) for Tooltip
                origin_book = core.analyze_context_vector([clean])
                if origin_book == "Neutral": 
                    origin_book = "Unknown Root"
                
                # Wrap in HTML with tooltip data
                punct = "".join(filter(lambda x: not x.isalpha(), w))
                html_word = f'<span class="word" data-origin="{clean} → {origin_book}">{z_word}</span>{punct}'
                trans_words_html.append(html_word)
            else:
                trans_words_html.append(w)  # Just punctuation
        
        # 2. Generate Sigil
        sigil, rtype = core.generate_mirror_sigil(" ".join(clean_text_for_analysis))
        
        # 3. Build HTML chunks
        english_paragraphs.append(f"<p>{sent}</p>")
        
        # Tooltip for the Sigil
        sigil_html = f'<span class="sigil" title="Structure: {rtype}">{sigil}</span>'
        
        zyn_sent = " ".join(trans_words_html)
        if zyn_sent.endswith("."): 
            zyn_sent = zyn_sent[:-1]
        
        zynthalic_paragraphs.append(f"<p>{zyn_sent} {sigil_html}</p>")

    # 4. Render Final HTML
    full_html = HTML_TEMPLATE.format(
        english_html="\n".join(english_paragraphs),
        zynthalic_html="\n".join(zynthalic_paragraphs),
        timestamp=datetime.datetime.now().strftime("%Y-%m-%d %H:%M")
    )
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(full_html)
        
    print(f"✅ Success! Open '{filename}' in your browser to see the professional layout.")

# ---------------------------------------------------------
# EXECUTE
# ---------------------------------------------------------
if __name__ == "__main__":
    # You can paste a whole chapter here
    sample_chapter = """
    The old man looked at the sea. The sea looked back at him.
    War is a cruel master, but peace is a gentle lie.
    The algorithm eats the world. The world feeds the algorithm.
    I seek the truth in the noise.
    """
    
    # Or load from a file:
    # with open("raw_anchors/Homer_Iliad.txt", "r") as f: sample_chapter = f.read()[:1000]
    
    publish_book(sample_chapter)